name: contributor_list
author: Caleb Denio
description: Easily list contributors on your README!
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: blue
  icon: users
inputs:
  commit_message:
    required: false
    default: Update contributors list
    description: The commit message when updating the README.md
  max_contributors:
    required: false
    default: 10
    description: Max number of contributors shown